name: Test

on:
  push:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Create test file
        run: echo "test12345" > test.txt

      - name: Install Packages
        run: npm install

      - name: Test self
        uses: ./ # Uses an action in the root directory
        with:
          sp_url: https://verimatrix.sharepoint.com/:f:/r/sites/productdocumentation
          sp_username: ${{ secrets.SP_USERNAME }}
          sp_password: ${{ secrets.SP_PASSWORD }}
          sp_folder: /Shared%20Documents/Watermarking/Standalone%20Android%20SDK
          sp_file_name: my_file.txt
          file: test.txt
